In [2]:
import sqlite3      # Library for  working with the SQLite database
import pandas as pd
import matplotlib.pyplot as plt

# Create connection to the SQLite database
conn = sqlite3.connect('Chinook_Sqlite.sqlite')

def run_query(query):
    """Function to run the SQL queries and easily return the results as a pandas DataFrame."""
    return pd.read_sql_query(query, conn)   # Tool from pd to process the SQL query and return the results as a DataFrame. Uses the query and "conn" which is basically the database we're working with.

In [4]:
# Gathering what are the tables before starting to query the database

query_schema = """ SELECT name FROM sqlite_master WHERE type = 'table'; """

run_query(query_schema)

             name
0           Album
1          Artist
2        Customer
3        Employee
4           Genre
5         Invoice
6     InvoiceLine
7       MediaType
8        Playlist
9   PlaylistTrack
10          Track

In [5]:
# Which are the 10 best-selling tracks?

query_top_tracks = """
SELECT Name AS Song, SUM(Quantity) AS Quantity_Sold
FROM Track JOIN InvoiceLine
ON InvoiceLine.TrackID = Track.TrackID
GROUP BY Song
ORDER BY Quantity_Sold DESC
LIMIT 10;
"""

run_query(query_top_tracks)

                        Song  Quantity_Sold
0                The Trooper              5
1                   Untitled              4
2    The Number Of The Beast              4
3        Sure Know Something              4
4       Hallowed Be Thy Name              4
5                   Eruption              4
6          Where Eagles Dare              3
7  Welcome Home (Sanitarium)              3
8             Sweetest Thing              3
9                  Surrender              3